# Site settings
title: CSU Online Learning Exchange
email: your-email@domain.com
description: "Developed and Maintained by Charles Sturt University's u!magine"
baseurl: "/csulx" # the subpath of your site, e.g. /blog/

#url: "http://yourdomain.com" # the base hostname & protocol for your site
encoding: utf-8

twitter_username: csuLX
github_username:  csuLX

# Setup for pages
include: ["_pages"]
permalink: /:categories/:title.html

# Setup for Categories
collections:
  applications:
    output: true
    permalink: /applications/:categories/:title.html
  strategies:
    output: true
    permalink: /strategies/:title.html
    layout: post

#Timezone
timezone: Australia/Sydney

# sass:
#   style: compressed

# Build settings
markdown: kramdown
