---
upload_path: "/images/practices"
frontmatter_file_url_template: "/images/practices"
body_file_url_template: "/images/practices"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections: 
